server:
  port: 8010

spring:
  application:
    name: LLM-Rag
  ai:
    dashscope:
      api-key: @dashscope.api.key@
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 768
